name: deploy-master
on: [push]
env:
  CI: false
jobs:
  deploy-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/AllenAnZifeng/blog_frontend.git
          npm run deploy -u "github-actions-bot <devops@github.com>"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

